### ISSUE TITLE
com.netflix.zuul.exception.ZuulException: Forwarding error

### ISSUE THREAD

**Issue by MadeInChina** [MadeInChina/PiggyMetrics#12]
The issue happened after using BlockingLoadBalancerClient 
```
    #The recommended implementation is BlockingLoadBalancerClient - add org.springframework.cloud:spring-cloud-loadbalancer in order to use it.
    loadbalancer:
      ribbon:
        enabled: false

```

```
com.netflix.zuul.exception.ZuulException: Forwarding error
6/14/2020 9:53:01 PM	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:198) ~[spring-cloud-netflix-zuul-2.2.3.RELEASE.jar!/:2.2.3.RELEASE]
```

Upgrade zuul to spring gateway.
