### ISSUE TITLE
Add JwtTokenStore documents

### ISSUE THREAD

**Issue by MadeInChina** [MadeInChina/PiggyMetrics#8]

**Comment by MadeInChina** [comment]
Core config
```
security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current
      token-info-uri: http://auth-service:5000/uaa/oauth/check_token
```
```
				"ResourceServerTokenServicesConfiguration.RemoteTokenServicesConfiguration.TokenInfoServicesConfiguration": [{
					"condition": "ResourceServerTokenServicesConfiguration.TokenInfoCondition",
					"message": "OAuth TokenInfo Condition found preferred token-info-uri property"
				}],
```

```
@Override
  public void configure(AuthorizationServerEndpointsConfigurer endpoints) {
    endpoints
        .tokenStore(tokenStore())
        .accessTokenConverter(accessTokenConverter())
        .authenticationManager(authenticationManager)
        .userDetailsService(userDetailsService);
  }

  @Override
  public void configure(AuthorizationServerSecurityConfigurer oauthServer) {
    oauthServer.tokenKeyAccess("permitAll()").checkTokenAccess("isAuthenticated()");
  }

  @Bean
  public JwtTokenStore tokenStore() {
    return new JwtTokenStore(accessTokenConverter());
  }

  @Bean
  public JwtAccessTokenConverter accessTokenConverter() {
    JwtAccessTokenConverter enhancer = new JwtAccessTokenConverter();
    enhancer.setSigningKey("123456");
    return enhancer;
  }
```
