### ISSUE TITLE
hystrix show host instances not correct.

### ISSUE THREAD

**Issue by MadeInChina** [MadeInChina/PiggyMetrics#9]

**Comment by MadeInChina** [comment]
Fixed by 
```
hystrix:
  stream:
# https://github.com/spring-cloud/spring-cloud-netflix/issues/740
#  if you set hystrix.stream.amqp.send-id=false to allow disabling of sending the context id as the metric id, Turbine AMQP then defaults to serviceId:host:port.
    queue:
      send-id: false
```
